# See https://github.com/probot/settings for more information.

repository:
  name: python4yahdlc
  description: Python binding of the yahdlc library
  homepage: https://pypi.python.org/pypi/python4yahdlc
  topics: python, python3, python-bindings, hdlc, network, yahdlc
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: develop
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: feature
    oldname: enhancement
    description: New feature
    color: 84b6eb
  - name: optimisation
    description: Optimisation
    color: 84b6eb

  - name: bug
    description: New bug
    color: ee0701
  - name: regression
    description: Software regression
    color: ee0701
  - name: security
    description: Security issue
    color: ee0701

  - name: android
    description: Android platform support issues
    color: 047277
  - name: linux
    description: Linux platform support issues
    color: 047277
  - name: macos
    description: Apple macOS platform support issues
    color: 047277
  - name: windows
    description: Microsoft Windows platform support issues
    color: 047277

  - name: duplicate
    description: Duplicate issue
    color: cccccc
  - name: invalid
    description: Invalid issue
    color: cccccc
  - name: on hold
    description: On hold (waiting for an answer, action required...)
    color: cccccc
  - name: won't fix
    description: The issue won't be fixed
    color: cccccc

  - name: help wanted
    description: Help wanted
    color: 33aa3f
  - name: question
    description: Question
    color: 33aa3f

  - name: documentation
    description: Documentation-related issue
    color: 2d2de2

  - name: good first issue
    description: Good first issue
    color: 7057ff

branches:
  - name: master
    protection:
      required_pull_request_reviews:
      required_status_checks:
        strict: false
        contexts:
          - continuous-integration/travis-ci
      enforce_admins: true
      restrictions:
  - name: develop
    protection:
      required_pull_request_reviews:
      required_status_checks:
      enforce_admins: false
      restrictions:
